<?php

namespace Reviz\FrontBundle\Repository;

/**
 * MeetupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetupRepository extends \Doctrine\ORM\EntityRepository
{
}
