<?php

namespace Reviz\FrontBundle\Repository;

/**
 * TaxonomyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonomyRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * allTerms
     *
     * @param $term
     * @return array
     */
    public function allTerms($term)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT t
                 FROM RevizFrontBundle:Taxonomy t
                 WHERE t.term = :term
                 ORDER BY tag.name ASC'
            );
        $query->setParameter('term', $term);

        return $query->getResult();
    }

    /**
     * allModulesByLevel
     *
     * @return array
     */
    public function allModulesByLevel($name)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT m
                 FROM RevizFrontBundle:Module m
                  WHERE m.parentId IN (
                  SELECT l.id
                  FROM RevizFrontBundle:Level l
                  WHERE l.name = :name
                  )
                 ORDER BY m.name ASC'
            );

        $query->setParameter('name', $name);

        return $query->getResult();
    }

    /**
     * nbResourceByModule
     *
     * @param $resource
     * @param $name
     * @return array
     */
    public function nbResourceByModule($resource, $name)
    {

        $resource = 'nb' . ucfirst(strtolower($resource));

        $dql = sprintf('
        SELECT SUM(c.%s) as nb
        FROM RevizFrontBundle:Category c
        WHERE c.parentId IN (
          SELECT m.id
          FROM RevizFrontBundle:Module m
          WHERE m.name = :name
        )
        ', $resource);

        $query = $this->getEntityManager()
            ->createQuery($dql);

        $query->setParameter('name', $name);

        return $query->getResult();
    }


    public function allCategoriesByModule($id)
    {

        $dql = sprintf('
        SELECT c
        FROM RevizFrontBundle:Category c
        WHERE c.parentId IN (
          SELECT m.id
          FROM RevizFrontBundle:Module m
          WHERE m.id = :id
        )
        ');

        $query = $this->getEntityManager()
            ->createQuery($dql);

        $query->setParameter('id', $id);

        return $query->getResult();
    }

    public function nbResources()
    {

        $dql = sprintf('
        SELECT SUM(t.nbCourse), SUM(t.nbMethod), SUM(t.nbExercice)
        FROM RevizFrontBundle:Taxonomy t
        ');

        $query = $this->getEntityManager()
            ->createQuery($dql);

        return $query->getResult();
    }

    public function search($name)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT m.name, m.id
                FROM RevizFrontBundle:Taxonomy m
                WHERE m.name LIKE :name
            ');

        $query->setParameter('name', $name . '%');

        return $query->getResult();
    }

}
