language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
env:
  - SYMFONY_VERSION=3.0.**
  - SYMFONY_VERSION=dev-master

before_script:
  - composer selfupdate
  - composer require symfony/symfony:${SYMFONY_VERSION}

script:
  - phpunit --coverage-text
  - vendor/bin/behat --suite=core