# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    parameter_name: je suis un paramètre sympa

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    reviz.regex:
        class: Reviz\FrontBundle\Utils\Regex

    reviz.antispam:
        class: Reviz\FrontBundle\Utils\AntiSpam
        arguments: ["@reviz.regex", "c'est foo", "%parameter_name%"]

#    reviz.exception:
#        class: Reviz\FrontBundle\Utils\Event\RevizException
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception }